"""Add account column to Transaction model

Revision ID: 847a0e100744
Revises: eb80e27f6491
Create Date: 2024-09-27 11:46:23.567887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847a0e100744'
down_revision = 'eb80e27f6491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('account')

    # ### end Alembic commands ###
